<h3><?= ucfirst(Zend_Controller_Front::getInstance()->getRequest()->getActionName());?></h3>

<div class="alert alert-info alert-dismissible fade in" role="alert" id="alert"> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
        <span aria-hidden="true">×</span></button> 
    
    <p id="p_msg"><?= $this->msg;?></p>
</div>

<form method="POST">
    <div class="form-group <?= (isset($this->errors['nome'])) ?'has-error':''?>">
        <label for="nome">Nome do Produto</label>
        <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do Produto" aria-describedby="descNome" 
            <?php if(Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'editar'){
               echo 'value="'.$this->produto['nome'].'"';
            } ?>
        >
        <?php if(isset($this->errors['nome'])){?>
        <span id="descNome" class="help-block"><?php echo $this->errors['nome']; ?></span>
        <?php } ?>
    </div>

    <div class="form-group <?= (isset($this->errors['local_id'])) ?'has-error':''?>">
        <label class="control-label" for="local_id">Local</label>
        <div class="input-group">
            <a type="button" class="input-group-addon" data-toggle="modal" data-target="#myModal">+</a>
            
            <select class="form-control" id="local_id" name="local_id" aria-describedby="descLocalId">
                <option value="">Selecione</option>
                <?php
                foreach ($this->locals as $local):
                    echo '<option value="' . $local->id . '"';
                    if(Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'editar' && $this->produto['local_id'] == $local->id){
                        echo ' selected ';
                    }
                    echo '>' . $this->escape($local->nome) . '</option>';
                endforeach;
                ?>
            </select>
            
        </div>
        <?php if(isset($this->errors['local_id'])){?>
        <span id="descLocalId" class="help-block"><?php echo $this->errors['local_id']; ?></span>
        <?php } ?>
    </div>
    
    <div class="form-group <?= (isset($this->errors['preco'])) ?'has-error':''?>">
        <label for="preco">Preço</label>
        <input type="text" class="form-control" id="preco" name="preco" placeholder="Preço" aria-describedby="descPreco"
            <?php if(Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'editar'){
               echo 'value="'.str_replace('.', ',', $this->produto['preco']).'"';
               
               /*
                * 8.5       1       1.89
                * 8,50      1,00    1,89
                * 
                */
            } ?>
        >
        <?php if(isset($this->errors['preco'])){?>
        <span id="descPreco" class="help-block"><?php echo $this->errors['preco']; ?></span>
        <?php } ?>
    </div>
    <button type="submit" class="btn btn-default">Salvar</button>
    
    
</form>
<?= $this->render('local/cadastrar_modal.phtml') ?>
<script>
    $('#preco').mask('000.000.000.000.000,00', {reverse: true});
    <?= $this->msg ? '' : '$("#alert").hide();' ;?>
    
    function cadastro_local (data){
        if(!data.ok){
            $('#p_msg').text(data.erro.message);
            $('#alert').fadeIn();
            return;
        }
        
        $('#p_msg').text("Local cadastrado com sucesso.");
        
        $('#local_id').html('').append($('<option>', {value:'', text:"Selecione"}));
        
        $.each(data.locals, function( index, value ) {
            $('#local_id').append( $('<option>', {
                value:value.id,
                text:value.nome
            }));
        });
        
        $('#local_id').val(data.new_id);
    }
    
</script>
<?php
// plugins
$this->headScript()->appendFile('/js/jquery.mask.min.js');
