<?php if(isset($this->alert)){?>
<div class="alert alert-<?= $this->alert['tipo'];?> alert-dismissible fade in" role="alert"> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">×</span></button> 
    <strong><?= $this->alert['titulo'];?></strong> <?= $this->alert['msg'];?> 
</div>
<?php } ?>
<a class="btn btn-primary"
    href="<?= $this->url(array('controller'=>'produto','action'=>'cadastrar'));?>"
>Cadastrar</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Produto</th>
            <th>Local</th>
            <th>Preço</th>
            
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->produtos as $prod): ?>
        <tr>
            <td><?= $prod->id?></td>
            <td><?= $prod->nome?></td>
            <td><?= $prod->local_nome?></td>
            <td>R$ <?= number_format($prod->preco, 2)?></td>
<!--            @TODO aria icon !!-->
            <td>
                <a href="<?= $this->url(array('controller'=>'produto','action'=>'editar','id'=>$prod->id));?>" 
                   class="glyphicon glyphicon-edit" aria-></a>
            </td>
<!-- /produto/editar/<?= $prod->id?> -->
            <td>
                <a href="<?= $this->url(array('controller'=>'produto','action'=>'excluir','id'=>$prod->id));?>" 
                   class="glyphicon glyphicon-remove" aria-></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    
</table>