<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cadastrar novo Local</h4>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="nome">Nome do Local</label>
                    <input type="text" class="form-control" id="nome" name="nome" 
                           placeholder="Nome do Local" aria-describedby="descNome">
                    <span id="descNome" class="help-block"></span>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="salvar()">Salvar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>