<!-- Modal -->
<div class="modal fade" role="dialog" id="myModal">
    <div class="modal-dialog">

        <!-- Modal content-->
        <form class="modal-content" onsubmit="salvar(); return false;" id="form_modal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cadastrar novo Local</h4>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="nome">Nome do Local</label>
                    <input type="text" class="form-control" id="nome" name="nome" 
                           placeholder="Nome do Local" aria-describedby="descNome">
                    <span id="descNome" class="help-block"></span>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="salvar()">Salvar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </form>
    </div>
</div>
<script>
    function salvar() {

        $.ajax({
            type: "POST",
            url: "<?= $this->url(array('controller' => 'local', 'action' => 'cadastrarJSON')) ?>",
            data: $('#form_modal').serialize()
        }).success(function (data) {
            cadastro_local(data);
        }).fail(function(){
            //msg erro HTTP
        }).always(function () {
            $('#myModal').modal('hide');
        });

        return false;
    }
</script>