<?php echo $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Bartolomeu S. Gusella">
    

    <title>Estoque Gusella</title>

    <?php
    
    // Bootstrap core JavaScript
    
    //scripts por causa do prepend ficam em ondem invertida ao que são chamados
    $this->headScript()->prependFile('/dist/js/bootstrap.min.js');
    $this->headScript()->prependFile('/js/jquery-1.11.3.js');
    
    echo $this->headScript();
    
    //Bootstrap core CSS
    $this->headLink()->appendStylesheet('/dist/css/bootstrap.min.css');
    //Custom styles for this template
    $this->headLink()->appendStylesheet('/dashboard.css');
    ?>
    
    <?php echo $this->headLink(); ?>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
      <?php echo $this->layout()->content ?>
  </body>
</html>
