<div class="container">
    <form class="col-sm-6 col-sm-offset-3" method="POST" 
        action="<?= $this->url(array('controller'=>'login', 'action'=>'logar')) ?>">
        <h2 class="">Estoque Gusella</h2>
        <h4>Faça login para acessar</h4>
        <?php if(isset($this->alert)){?>
            <div class="alert alert-danger alert-dismissible fade in" role="alert"> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">×</span></button> 
                <strong><?= $this->alert['titulo'];?></strong> <?= $this->alert['msg'];?> 
            </div>
        <?php } ?>
        <div class="form-group <?= (isset($this->errors['login'])) ?'has-error':''?>">
            <label for="login" class="sr-only">Usuário</label>
            <input type="text" name="login" id="login" class="form-control" placeholder="Usuário" required autofocus>
            <?php if(isset($this->errors['login'])){?>
                <span id="descUser" class="help-block"><?php echo $this->errors['login']; ?></span>
            <?php } ?>
        </div>
        <div class="form-group <?= (isset($this->errors['password'])) ?'has-error':''?>">
            <label for="password" class="sr-only">Senha</label>
            <input type="password" id="password" name="password" class="form-control" placeholder="Senha" required>
            <?php if(isset($this->errors['password'])){?>
                <span id="descUser" class="help-block"><?php echo $this->errors['password']; ?></span>
            <?php } ?>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Acessar</button>
    </form>

</div>